### PR TITLE
Add priorityClassName to pods specs

### PR DESCRIPTION
**Pull request by amirschw**
Add the ability to define `priorityClassName` for KEDA and Metrics Adapter pods in `values.yaml`.

### CODE REVIEW

**Comment by jeffhollan** [comment]
Looks good but if you want to ship the update so folks can start using it you’ll need to run the steps in the README to generate a new package.

**Comment by tomkerkhove** [comment]
I've merged it as we are good for now I think!

**Comment by oronboni** [comment]
Please create new official chart (version 1.3.2) with this change.

**Comment by tomkerkhove** [comment]
We typically release every 3 weeks, it should go out this week somewhere normally.

**Comment by tomkerkhove** [comment]
You can still build the chart yourself btw

**Comment by oronboni** [comment]
@tomkerkhove If you use Jenkins or Azure DevOps I can contribute by build a process that create the chart automatic.
I strongly prefer that the charts will be taken from one place "official chart location"

**Comment by tomkerkhove** [comment]
> I strongly prefer that the charts will be taken from one place "official chart location"

What do you mean by that? That you'd rather pull it from our artifact repository rather than building yourself?

> @tomkerkhove If you use Jenkins or Azure DevOps I can contribute by build a process that create the chart automatic.

I'll let @ahmelsayed comment on this but think we do this on purpose as our Helm charts are part of this repo and want to do manual deploy triggers.

**Pull request merged**
