### PR TITLE
Use apiextensions.k8s.io/v1 instead of apiextensions.k8s.io/v1beta1

### PR DESCRIPTION
**Pull request by tomkerkhove**
Use apiextensions.k8s.io/v1 instead of apiextensions.k8s.io/v1beta1 to fix linting issue

### CODE REVIEW

**Comment by zroubalik** [comment]
@tomkerkhove is this something for v2? Then we should update the CRDs in the helm, ie. migrate those from kedacore/keda

**Comment by tomkerkhove** [comment]
This is mainly to fix the linting issue which is failing on this, but it's only supported as of v1.16 (https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/) so I'm wondering if this is even good to go or not.

**Comment by zroubalik** [comment]
Yeah, this issue is decribed here: https://github.com/kedacore/keda/issues/701

I think that it is not needed to change it now, `v1beta1` is still going to work. If we do the change we would lost support on k8s < 1.16 as you mentioned.

We can change this later as part of some 2.x release, it is not as big change is it could look.

**Comment by tomkerkhove** [comment]
Sounds good to me, we'll just ignore that one error for now then.

What about the name of the cluster role binding?

**Comment by zroubalik** [comment]
> What about the name of the cluster role binding?

The name is taken from the Cluster role name it is referring to `system:auth-delegator`.

But it is ok to rename it, if you do so, please change it in the kedacore/keda repo as well, just for the consistency.

**Comment by tomkerkhove** [comment]
Let's just keep things as is. This is nothing major.

**Pull request closed without merging**
