### PR TITLE
fix: Use correct name label for pod monitor for Metrics adapter

### PR DESCRIPTION
**Pull request by elihai-risk**
correcting the name of the target

_Provide a description of what has been changed_

### Checklist

- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/charts/blob/master/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [ ] A PR is opened to update KEDA core ([repo](https://github.com/kedacore/keda)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] README is updated with new configuration values *(if applicable)*

Fixes #

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]
Thank you!

**Comment by tomkerkhove** [comment]
Can you fix DCO please?

**Review by zroubalik — APPROVED** [review]

**Comment by tomkerkhove** [comment]
Would you mind fixing DCO so we can merge @elihai-risk?

**Comment by tomkerkhove** [comment]
@elihai-risk Any chance you are able to complete this PR?

Fixing the DCO issue should be fairly easy to tackle, learn more in our [contribution guide](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what).

**Review by arschles — APPROVED** [review]
Looks great @elihai-risk, thank you! There's a conflict that needs resolving, and the DCO needs to be fixed as well. We're happy to help with either thing, just feel free to ask (if you'd like to ask in private, I can be reached on the Kubernetes, CNCF, or Gophers slack groups at `arschles`)

**Pull request merged**
