### PR TITLE
Add recommended kubernetes labels to helm chart

### LINKED ISSUE #536: Add OTEL collector as dep and enable de integration on KEDA chart tests
### Use-Case

Tell us more what you'd like to achieve

### Specification

- [ ] Demand #1

### PR DESCRIPTION
**Pull request by Cottonglow**
The intent behind this PR is to open a discussion and decide on what labels we want to add, the values we want and which resources they should be on (It is recommended to apply the labels on every resource object - https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/).

 I picked the labels that seemed reasonable to me and the values that made sense.

### Checklist

- [x] A PR is opened to update the labels in the keda repository - https://github.com/kedacore/keda/pull/596

Fixes https://github.com/kedacore/keda/issues/536

### CODE REVIEW

**Comment by jeffhollan** [comment]
Thanks @Cottonglow - LGTM.  @ahmelsayed let me know if you have any concerns

**Comment by ahmelsayed** [comment]
@Cottonglow can you rebase or merge @robece changes in #17

**Comment by Cottonglow** [comment]
@ahmelsayed Done :)

**Comment by ahmelsayed** [comment]
Thank you @Cottonglow :)

**Pull request merged**
