### PR TITLE
adding operator namespace env var

### PR DESCRIPTION
**Pull request by arschles**
This patch is required for the operator to start properly. We need to tell it the namespace of the routing table `ConfigMap`

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/charts/blob/master/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- ~A PR is opened to update KEDA core ([repo](https://github.com/kedacore/keda)) *(if applicable, ie. when deployment manifests are modified)*~
- [x] README is updated with new configuration values *(if applicable)*

Fixes #

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]
LGTM - Did you intentionally bundle the chart or not?

**Comment by arschles** [comment]
@tomkerkhove I followed the [release instructions](https://github.com/kedacore/charts/blob/master/CONTRIBUTING.md#shipping-a-new-version), which had me bundle the chart in this PR. is that not right?

**Comment by tomkerkhove** [comment]
Yes it is, but we typically only do that once the new version is published - Would you mind holding off next time please?

If somebody wants to install the latest of this chart they will now have issues (unless the container is already pushed but release was not created)

**Comment by arschles** [comment]
Yes, this makes sense. I'll note in the [release process documentation](https://github.com/kedacore/http-add-on/blob/main/RELEASE-PROCESS.md) that any chart PRs related to a new release should only be merged _after_ all other release artifacts are published.

**Pull request merged**
