### PR TITLE
Fix servicemonitor relabeling

### PR DESCRIPTION
**Pull request by kubroid**
Trying to deploy keda using this values file:
```
prometheus:
  operator:
    enabled: true
    port: 8080
    serviceMonitor:
      enabled: true
      relabellings:
      - regex: (rest_client_.*|go_.*|workqueue_.*)
        action: drop
```
Result is:
```helm template -f a.yaml -n keda . 
Error: YAML parse error on keda/templates/manager/servicemonitor.yaml: error converting YAML to JSON: yaml: line 20: did not find expected key
```

### Checklist

- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #
Helm chart fixed to use right indents.
```
helm template -f a.yaml -n keda . | grep ServiceMonitor -A20
kind: ServiceMonitor
metadata:
  name: keda-operator
  annotations:
    {}
  labels:
    app.kubernetes.io/name: keda-operator    
    helm.sh/chart: keda-2.10.2
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.10.1
spec:
  endpoints:
  - port: metrics
    path: /metrics
    relabelings:
      - action: drop
        regex: (rest_client_.*|go_.*|workqueue_.*)
  namespaceSelector:
  ```

### CODE REVIEW

**Comment by JorTurFer** [comment]
Looking good, could you update the test values yaml to use service monitor on all the resources with a relabeling (to prevent this in the future)?
You can achieve it modifying this section: https://github.com/kedacore/charts/blob/main/.github/workflows/ci-core.yml#L107-L115

**Comment by kubroid** [comment]
Sure. Test data updated. Templating is [ok](https://github.com/kedacore/charts/actions/runs/5185032733/jobs/9344506972?pr=456#step:11:9953), but helm deploy failing on timeout. Is it common?

**Comment by JorTurFer** [comment]
> Is it common?

No it isn't. Metrics server pod is failing to start, which shouldn't happen. I don't think that it's related with your commit, let me check

**Comment by kubroid** [comment]
The only idea I have is an invalid regex expression. Had no chance to check it in real deployment.

**Comment by JorTurFer** [comment]
> The only idea I have is an invalid regex expression. Had no chance to check it in real deployment.

I don't think that it's enough to break the metrics server startup as it's something related with Prometheus, not with the metrics server itself. I'll test it locally during the morning

**Comment by JorTurFer** [comment]
> Thanks Jorge. One more thing to discuss: here is [inconsistency](https://github.com/kedacore/charts/blob/main/keda/templates/metrics-server/servicemonitor.yaml?rgh-link-date=2023-06-06T06%3A57%3A40Z#L41-L42) between relabel**l**ings and relabelings. Do we want to fix this?

It'd be nice, but we should maintain backward compatibility, so we can't just rename it, we have to maintain both, the old one and the new one (adding a deprecation note on the old one)

**Comment by JorTurFer** [comment]
It's because there is a PR merged in core but still not merged here: https://github.com/kedacore/charts/pull/432
Let me push it

**Comment by JorTurFer** [comment]
Could you rebase your branch? The fix has been merged

**Comment by kubroid** [comment]
I'm on top of main:
```
* 0bd1bc1 - (18 hours ago) Fix servicemonitor relabeling - Alexey Kubrinsky (HEAD -> fix-servicemonitor, origin/fix-servicemonitor)                                                                                                                                                       
* c5fad71 - (5 days ago) fix(http-add-on): Fix resources variables for the http-add-on deploym… (#454) - Jocelyn Thode (origin/main, origin/HEAD, main)                                                                                                                                   
```

**Comment by kubroid** [comment]
Jorge, please check last [commit](https://github.com/kedacore/charts/pull/456/commits/94950a654eb943da5f2c4afd1d02911545644f96). Made relabelling deprecated. Is it good?

**Comment by JorTurFer** [comment]
I think so.
Do we need to create an issue for the deprecation @tomkerkhove ?

**Review by tomkerkhove — APPROVED** [review]

**Comment by tomkerkhove** [comment]
Yes, we should follow https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md#introducing-new-deprecations.

I'll do this

**Pull request merged**
