### PR TITLE
fix: add configurable automountServiceAccountToken

### PR DESCRIPTION
**Pull request by stefan-caraiman**
This PR makes `automountServiceAccountToken` configurable for the deployment definitions.

### Checklist

- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] README is updated with new configuration values *(if applicable)* [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#documentation)
- [x] A PR is opened to update KEDA core ([repo](https://github.com/kedacore/keda)) *(if applicable, ie. when deployment manifests are modified)*

Fixes #

- configurable `automountServiceAccountToken` option in pod definitions

### CODE REVIEW

**Comment by JorTurFer** [comment]
Hello,
What is the goal of this change? I mean, this change suggests that the service account token is something optional, and it isn't. If you don't mount the service account tokens KEDA won't work as all the components have to interact with k8s api server.
Am I missing something?

**Comment by stefan-caraiman** [comment]
@JorTurFer @tomkerkhove PTAL 👋

**Comment by JorTurFer** [comment]
I think that you should expect the rule directly in the Azure Security Center rather than  "hacking" the rule. @tomkerkhove ?

**Comment by stefan-caraiman** [comment]
No harm in setting explicit definitions though, at least imo since it seems more of a hack that the internal K8s admission controller does the volume mount of the tokens without the user being aware of it.

Nevertheless will leave it up to you to decide 👍

**Comment by JorTurFer** [comment]
I'm not directly against this tbh, but I'd like to see other folks thoughts.
@zroubalik  @tomkerkhove ?

**Comment by stefan-caraiman** [comment]
@JorTurFer i will go ahead and close this PR in favour of #625 thanks

**Pull request closed without merging**
