### PR TITLE
fix: allow user to configure metrics API server port

### PR DESCRIPTION
**Pull request by doctorpangloss**
Signed-off-by: Benjamin Berman <>

### Checklist

- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [X] A PR is opened to update KEDA core ([repo](https://github.com/kedacore/keda)) *(if applicable, ie. when deployment manifests are modified)*
- [x] README is updated with new configuration values *(if applicable)*

Relates to https://github.com/kedacore/keda/issues/3576

### CODE REVIEW

**Comment by JorTurFer** [comment]
Could you sign your commit? We need that all the commits are sign to be able to merge the PR

**Review by JorTurFer — APPROVED** [review]

**Comment by doctorpangloss** [comment]
> Could you sign your commit? We need that all the commits are sign to be able to merge the PR

Done

**Review by tomkerkhove — CHANGES_REQUESTED** [review]
Can you update the README with this new setting please?

**Comment by doctorpangloss** [comment]
> Can you update the README with this new setting please?

The README is updated and correct. It always had `service.portHttpTarget` specified. It should have been used. This fix now uses it correctly.

**Review by tomkerkhove — APPROVED** [review]
Sounds good, thanks!

**Comment by hajdukda** [comment]
Hi, when dis will be released ? I've just pulled kedacore/keda 2.8.2 and inside there still is:
```
          args:
          - /usr/local/bin/keda-adapter
          - --secure-port={{ .Values.service.portHttpsTarget }}
          - --logtostderr=true
```

**Pull request merged**
