### PR TITLE
chore: Ship v0.2.1 chart for HTTP add-on

### PR DESCRIPTION
**Pull request by tomkerkhove**
Ship v0.2.1 chart for HTTP add-on, releasing #210, #210 & #225.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@arschles This includes https://github.com/kedacore/charts/pull/225, but I think this is not supported yet or is it?

**Review by JorTurFer — APPROVED** [review]

**Review by arschles — APPROVED** [review]
LGTM. the change in https://github.com/kedacore/charts/pull/225 will expose configuration that isn't valid until we release a new version of the HTTP Addon. that should be early next week. I think that's ok, though, because we're going to release a `v0.3.0` for that.

**Comment by tomkerkhove** [comment]
@arschles I will not include it in the release notes so we can add it to v0.3 to avoid issues.

**Comment by arschles** [comment]
What issues do you foresee, @tomkerkhove?

**Pull request merged**
