### PR TITLE
Ship KEDA 2.0

### PR DESCRIPTION
**Pull request by tomkerkhove**
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>

### CODE REVIEW

**Comment by jeffhollan** [comment]
Looks good but did you rename the apiregistration version to v1 from v1beta1 (had that change in my PR). It's not a huge deal but pops a warning in k8s 1.19

**Review by jeffhollan — APPROVED** [review]

**Comment by zroubalik** [comment]
@tomkerkhove @jeffhollan we should definitely use `apiregistration v1`, if it is not in here, we shoud fix that ;)

**Comment by tomkerkhove** [comment]
Well spotted @jeffhollan, thanks! Didn't know you were around already 😅

**Review by zroubalik — APPROVED** [review]
LGTM

**Pull request merged**
