### PR TITLE
feat(http-add-on): Provide support for scheduling highly available across node per zone

### PR DESCRIPTION
**Pull request by tomkerkhove**
Provide support for scheduling highly available across node per zone

### Checklist

- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] README is updated with new configuration values *(if applicable)*

Fixes https://github.com/kedacore/charts/issues/359

### CODE REVIEW

**Review by JorTurFer — COMMENTED** [review]
Why not just `podTopologySpread`? I mean, does `highAvailability` give value here? For HA scenarios there are other things required like multi replicas, pod disruption budgets, etc...
I'd put `podTopologySpread`  inside each component because they can be in different pools for different reasons, IMO each component should be configurable

**Comment by tomkerkhove** [comment]
> Why not just `podTopologySpread`? I mean, does `highAvailability` give value here? For HA scenarios there are other things required like multi replicas, pod disruption budgets, etc...

Because I'll add more things under that umbrella for future features, such as pod disruption budgets :) We tend to have too many top level things and should provide more structure.

> I'd put `podTopologySpread` inside each component because they can be in different pools for different reasons, IMO each component should be configurable

The chart is having too many knobs while they will generally be enabled for the same thing. One will not enable HA for interceptor; but not for the others. That makes no sense to me.

**Comment by JorTurFer** [comment]
> The chart is having too many knobs while they will generally be enabled for the same thing. One will not enable HA for interceptor; but not for the others. That makes no sense to me.

Are all the components ready for HA? I think the scaler can't have more than 1 instance. This could be more confusing if users think that they have an HA configuration but we have a single instance. TBH, I prefer to expose all the parameters but not doing "black magic" under the hood, we can expose the topology key, with an explanation as comments in value file or having an example's folder rather than hidding the config

**Comment by tomkerkhove** [comment]
I think your approach is coming from a technical perspective and mine is around making it simple for end-users.

HA is more than running multiple instances and I think we should start with a general configuration, and give more granular knobs if people want them. That way, the configuration is simple until we need to go more advanced.

**Comment by tomkerkhove** [comment]
Let's see what @zroubalik thinks and I'll adapt accordingly

**Comment by JorTurFer** [comment]
@zroubalik , what do you think?

**Comment by tomkerkhove** [comment]
@zroubalik Thoughts?

**Comment by JorTurFer** [comment]
Kindly reminder @zroubalik , wdyt?

**Comment by tomkerkhove** [comment]
It's a nob they can turn on so that we schedule things highly available; but it's fine - Let's abandon this PR

**Pull request closed without merging**
