### PR TITLE
Update GitHub repository URL for Cosmos DB external scaler

### PR DESCRIPTION
**Pull request by JatinSanghvi**
Updated paths to repository and Docker image.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/charts/blob/master/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

### CODE REVIEW

**Review by tomkerkhove — CHANGES_REQUESTED** [review]
LGTM, but we should delete the old doc given our v0.1.0 image is still the old one, can you ever this please?

**Comment by JatinSanghvi** [comment]
@tomkerkhove, can you elaborate on which file you are referring to. For clarification, I have updated the v0.1.0 release image to new path.

**Comment by JorTurFer** [comment]
I prefer it like `{external|add-on}-scaler-{xxxxx}`. For the moment we have these cases but, imagine a case with IDK, 15 different elements, they will be ordered because the common part will be at the start.

Apart for that "ordering" thing, I don't have a strong opinion. What could the impact of changing http-add-on chart be? I mean, if rename it now is a drama, we could keep it as it is and adapt the others

**Comment by tomkerkhove** [comment]
It would be a new chart next to the existing one, I'm afraid. But that should not be the showstopper

**Comment by zroubalik** [comment]
The HTTP add on has more images, it is not just scaler:
https://github.com/orgs/kedacore/packages?repo_name=http-add-on

So I'd say it is more like:
`add-on-http-scaler`
`add-on-http-interceptor`
`add-on-foo-bar`
...

And for the external scalers:
`external-scaler-azure-cosmos-db`
`external-scaler-baz`

**Comment by tomkerkhove** [comment]
Agree from my side, what do you think @JorTurFer ?

**Comment by JorTurFer** [comment]
me too

**Comment by zroubalik** [comment]
So let's wait what @arschles thinks about this :)

**Review by tomkerkhove — APPROVED** [review]
LGTM - Just waiting for @arschles his opinion

**Comment by arschles** [comment]
Sorry folks, I've been out on holiday and I'm just catching up now!

I agree with you @zroubalik in your comment at https://github.com/kedacore/charts/pull/204#issuecomment-978984313. For me, it doesn't seem to make sense to have the scaler be `external-scaler-http-addon` and have the other two be `add-on-http-{operator, interceptor}`.

**Comment by tomkerkhove** [comment]
Sounds good - Then the only change we have to do is rename the Helm chart for HTTP add-on unless we just keep this as-is?

**Pull request merged**
