### PR TITLE
Ship v2.0.1 of our Helm chart

### PR DESCRIPTION
**Pull request by tomkerkhove**
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Switching to v2.1.0 since we're adding a new feature; full notes are here:

> *Chart: v2.1.0 | App: v2.0.0
> 
> Minor improvements to how KEDA can be configured & use Helm v2 API version.
> 
> ## TL;DR
> ```shell
> helm repo add keda https://kedacore.github.io/charts
> helm install keda/keda
> ```
> 
> ## What is new?
> ### Features
> 
> - Support for adding annotations to service (#105)
> 
> ### Fixes / Changes
> 
> - Change Helm Chart API version to v2 (#101)
> - Improved documentation on watching namespaces (#107)
> - Update CRDs (#108)
> 
> ### Breaking Changes
> 
> None.
> 
> ### Removal
> 
> None.
>

**Comment by zroubalik** [comment]
Charts 2.1.0 should be based on KEDA 2.1.0. If this charts release will be based on KEDA 2.0.0, how would you release chart for the upcoming KEDA 2.1.0?
 It is bringing a lot of confusion IMHO

**Comment by tomkerkhove** [comment]
The app version of 2.1 chart is 2.0, if we would ship app 2.1, chart version would be 2.2.

That's why versions are seperate in Helm, but if you want I can revert it to 2.0.1 but it's not fully semver but I'm ok with either.

**Comment by zroubalik** [comment]
My opinion - definitely 2.0.1,  Introducing 2.1 would bring too much confusion for the next releases

**Comment by tomkerkhove** [comment]
Self-approving as discussed with @zroubalik once the change is reverted

**Pull request merged**
