### PR TITLE
chore: Ship KEDA chart v2.6.1

### PR DESCRIPTION
**Pull request by tomkerkhove**
Ship KEDA v2.6.1 to include #239 but giving some time to hopefully have #236 as part of this version

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Wait two days to see if we can incorporate #236

### CODE REVIEW

**Comment by JorTurFer** [comment]
Don't forget to update the chart version in readme.md

**Comment by tomkerkhove** [comment]
I was following your PR from yesterday but apparently it was not there as well 😅 
https://github.com/kedacore/charts/pull/240

Do you mean on https://github.com/kedacore/charts/#browse-all-our-helm-charts or where should it be updated?

**Comment by JorTurFer** [comment]
> I was following your PR from yesterday but apparently it was not there as well 😅 #240
> 
> Do you mean on [kedacore/charts#browse-all-our-helm-charts](https://github.com/kedacore/charts/#browse-all-our-helm-charts) or where should it be updated?

F**k me... I didn't push that commit 😢 
Let me update it

**Comment by JorTurFer** [comment]
https://github.com/kedacore/charts/pull/243
In fact, we added a specific point in the release process to do it

**Pull request merged**
