### PR TITLE
Fixed affinity and tolerations helm chart issue

### PR DESCRIPTION
**Pull request by viperKiran**
I have found affinity and tolerations in deployments are indented wrongly and added Pod Disruption Budget template for keda and metrics.

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Since it's shipping a new version it would be good to have @ahmelsayed his signoff as well

**Comment by tomkerkhove** [comment]
Actually I would suggest not to ship a new version yet and waith for new release cycle

**Comment by viperKiran** [comment]
Thanks, @tomkerkhove for approving this. I am wondering about the merge conflict since I don't have write access. Will maintainers take care of it?

**Comment by tomkerkhove** [comment]
That's actually something you can fix by merging master in your branch and fixing the conflicts.

Would you mind removing the changes that ship a new version as well please?

**Comment by viperKiran** [comment]
@tomkerkhove Done as you wish. Let me know if you have any concerns.

**Comment by tomkerkhove** [comment]
LGTM, thanks for the contribution @viperKiran!

**Pull request merged**
