### PR TITLE
Ship KEDA 2.0.0-beta1.1

### PR DESCRIPTION
**Pull request by tomkerkhove**
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>

Shipping #69

### CODE REVIEW

**Comment by zroubalik** [comment]
`2.0.1-beta` ? If you want to release a new beta version, the correct name should be something like `2.0.0-beta2`

**Comment by zroubalik** [comment]
But if we are about to release `2.0.0-beta2` charts, I think that we should release `2.0.0-beta2` in `kedacore/keda` as well.

**Comment by tomkerkhove** [comment]
Actually it's just a patch of the Helm chart 
New beta might make sense but not sure if we should go to kedacore/keda since nothing has changed? 🤔

**Comment by zroubalik** [comment]
Yeah, but you are patching (thus updating) the `Beta` version, not `2.0.0`. Therefore it should be probably named `2.0.0-beta1.1`

**Comment by tomkerkhove** [comment]
Makes sense, shall I use that?

**Review by zroubalik — APPROVED** [review]
LGTM

**Pull request merged**
