### PR TITLE
Remove support for Helm v2.x

### LINKED ISSUE #81: Remove support for Helm v2.x
Remove support for Helm v2.x since it's officially end-of-life.

### PR DESCRIPTION
**Pull request by tomkerkhove**
Remove support for Helm v2.x.

Closes #81

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Happy to bump to `2.0.0-rc-2` if we want

**Comment by tomkerkhove** [comment]
Thought on this @zroubalik ?

**Comment by zroubalik** [comment]
@tomkerkhove I agree. Do you want it to be in RC2? (sorry, I missed that)

**Comment by tomkerkhove** [comment]
Maybe good to do that indeed but no worries, I'll update rc2 on Monday with this PR!

**Comment by tomkerkhove** [comment]
We're good to go!

**Pull request merged**
