### PR TITLE
Update comments and suggested defaults

### PR DESCRIPTION
**Pull request by kamialie**
It seems that currently the description about [root _affinity_ setting](https://github.com/kedacore/charts/blob/main/keda/values.yaml#L515) is not correct, based on template [here](https://github.com/kedacore/charts/blob/main/keda/templates/webhooks/deployment.yaml#L165).

Also I assume that suggested root affinity would like to split all components across the nodes, not only operator and metrics-server.

Lastly for consistency I applied name of the admissions webhook to its affinity suggestion to follow similar suggestions for operator and metrics-server.

### Checklist

- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] README is updated with new configuration values *(if applicable)* [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#documentation)
- [x] A PR is opened to update KEDA core ([repo](https://github.com/kedacore/keda)) *(if applicable, ie. when deployment manifests are modified)*

### CODE REVIEW

**Comment by kamialie** [comment]
I haven't created an issue, as it seems to be an easy fix. However, if that's the proper workflow, and if these changes are worth going forward, I can do that.

**Comment by kamialie** [comment]
It seems like documentation was not updated on this [MR](https://github.com/kedacore/charts/pull/640), so you will see one related line being removed in this MR.

**Review by JorTurFer — APPROVED** [review]
Thanks! ❤️

**Comment by JorTurFer** [comment]
Could you sign the commit please?

**Comment by kamialie** [comment]
Now done :)

**Review by zroubalik — APPROVED** [review]

**Pull request merged**
