### PR TITLE
Adding disable-compression flag for both operator and metrics-server

### PR DESCRIPTION
**Pull request by ckuduvalli**
Disable response compression for k8s restAPI in client-go

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] A PR is opened to update KEDA core ([repo](https://github.com/kedacore/keda)) *(if applicable, ie. when deployment manifests are modified)*
- [x] README is updated with new configuration values *(if applicable)*

Fixes #

### CODE REVIEW

**Review by JorTurFer — COMMENTED** [review]
maybe we should give the option to end-user to modify this with values file.
@kedacore/keda-helm-contributors ?

**Comment by ckuduvalli** [comment]
@JorTurFer I have added the disable-compression as extraArgs in values.yaml. Please check. If this should be done, then I dont need to add disable-compression explicitly in the 2 deployment files

**Comment by JorTurFer** [comment]
mmm, I'm not sure about how is implemented. I mean, we are passing the arg always with these lines 

- https://github.com/kedacore/charts/pull/326/files#diff-a968951b0eec36d4f700dcc751e44e8403f4c9a586335df6920448eea5b29224R66
- https://github.com/kedacore/charts/pull/326/files#diff-41ba317cf4bc08a6007bec23e07ddd444808d713c06962463ba85be61f2df4faR93

Maybe as this is a specific feature, we could pass the value to the chart always (instead of using exta args), I mean, something like:
```yaml
          args:
          - --leader-elect
          - --disable-compression={{ .Values.operator.disableCompresion}}
          - "--zap-log-level={{ .Values.logging.operator.level }}"
          - "--zap-encoder={{ .Values.logging.operator.format }}"
```
WDYT?

**Comment by tomkerkhove** [comment]
> mmm, I'm not sure about how is implemented. I mean, we are passing the arg always with these lines
> 
> * https://github.com/kedacore/charts/pull/326/files#diff-a968951b0eec36d4f700dcc751e44e8403f4c9a586335df6920448eea5b29224R66
> * https://github.com/kedacore/charts/pull/326/files#diff-41ba317cf4bc08a6007bec23e07ddd444808d713c06962463ba85be61f2df4faR93
> 
> Maybe as this is a specific feature, we could pass the value to the chart always (instead of using exta args), I mean, something like:
> 
> ```yaml
>           args:
>           - --leader-elect
>           - --disable-compression={{ .Values.operator.disableCompresion}}
>           - "--zap-log-level={{ .Values.logging.operator.level }}"
>           - "--zap-encoder={{ .Values.logging.operator.format }}"
> ```
> 
> WDYT?

I agree with this proposal; it's more user-frienly

**Comment by tomkerkhove** [comment]
What is the status on this PR?

**Comment by ckuduvalli** [comment]
@JorTurFer @tomkerkhove 
Please check now

**Review by JorTurFer — COMMENTED** [review]
LGTM! Could you check why the CI check are failing?

**Comment by Adarsh-verma-14** [comment]
Hi @JorTurFer, @zroubalik ,  I can see that there is no activity for CI checks failing from some months so if all of you don't mind can i fix it ?

**Comment by zroubalik** [comment]
> Hi @JorTurFer, @zroubalik , I can see that there is no activity for CI checks failing from some months so if all of you don't mind can i fix it ?

Yes please! 

@ckuduvalli FYI

**Comment by JorTurFer** [comment]
I close this PR in favor of https://github.com/kedacore/charts/pull/554

**Pull request closed without merging**
