### PR TITLE
Update cloudeventsource type list

### PR DESCRIPTION
**Pull request by SpiritZhou**
Update cloudeventsource type list

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Relates to https://github.com/kedacore/keda/issues/3524

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]

**Comment by tomkerkhove** [comment]
@SpiritZhou Can you fix the CI please?

**Comment by zroubalik** [comment]
@SpiritZhou could you please fix the build?

**Review by zroubalik — COMMENTED** [review]
@SpiritZhou any update on this please?

**Comment by SpiritZhou** [comment]
I think my change is simple but as the CI is broken, I cannot see any build problem now.

**Comment by JorTurFer** [comment]
It was a CI problem, the fix is merged and I've rebased your PR

**Pull request merged**
