### PR TITLE
patch: added targetPendingRequests in spec of http-add-on

### PR DESCRIPTION
**Pull request by avinash31d**
Signed-off-by: Avinash Rai <avinash31d@gmail.com>

Added the missing spec.targetPendingRequests in http-add-on crd.yaml in chart-release branch
```
              targetPendingRequests:
                description: Value for the pending requests that the scaler will return to KEDA
                type: integer
```

This is same as [https://github.com/kedacore/charts/pull/230](230) please delete [https://github.com/kedacore/charts/pull/230](230)

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@arschles Should we ship a new version or wait on the next minor release?

**Review by arschles — APPROVED** [review]
Thanks so much for this @avinash31d !

**Comment by arschles** [comment]
@tomkerkhove let's ship a new version. similar to how we shipped a `v0.2.1`, I don't think there's a need to update any images in the http-add-on repo.

**Comment by tomkerkhove** [comment]
Sounds good to me!

**Comment by avinash31d** [comment]
thanks for merging

**Pull request merged**
