### PR TITLE
test: Deploy Helm charts on N+5 different Kubernetes versions

### PR DESCRIPTION
**Pull request by tomkerkhove**
Deploy Helm charts on N+5 different Kubernetes versions to ensure we are handling feature usage correctly with respect to Kubernetes versions.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/charts/blob/master/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

### CODE REVIEW

**Comment by zroubalik** [comment]
@tomkerkhove might be worth to include similar action for kedacore/keda and run it as part of nightly.

**Comment by tomkerkhove** [comment]
@zroubalik Would that be this one? https://github.com/kedacore/keda/blob/main/.github/workflows/nightly-e2e.yml

**Comment by zroubalik** [comment]
Yeah, just add the same thing there to a new job.

Run Kind and deploy KEDA there and check that it has been deployed correctly

**Comment by tomkerkhove** [comment]
Created https://github.com/kedacore/keda/issues/2392 for it and will do it later this month.

**Pull request merged**
